from sqlalchemy import Column, String, Text
from .base import BaseModel


class WorkflowAlert(BaseModel):
    """Operational workflow alert generated by the AI Co-Pilot scanner.

    entity_type: "AE", "Visit", or "Milestone"
    entity_id:   UUID of the referenced record
    alert_type:  "bottleneck", "deadline_risk", or "delay"
    message:     Plain-language operational alert message (from Claude)
    severity:    "low", "medium", or "high"
    created_at is inherited from BaseModel
    """
    __tablename__ = "workflow_alerts"

    entity_type = Column(String(20), nullable=False)
    entity_id   = Column(String(36), nullable=False, index=True)
    alert_type  = Column(String(30), nullable=False)
    message     = Column(Text, nullable=False)
    severity    = Column(String(10), nullable=False, index=True)
