"""add ai risk fields to adverse events

Revision ID: c4971b361024
Revises: 
Create Date: 2026-09-19 00:41:03.974396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4971b361024'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adverse_events', sa.Column('ai_risk_level', sa.String(length=20), nullable=True))
    op.add_column('adverse_events', sa.Column('ai_reasoning', sa.Text(), nullable=True))
    op.add_column('adverse_events', sa.Column('ai_flagged_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverse_events', 'ai_flagged_at')
    op.drop_column('adverse_events', 'ai_reasoning')
    op.drop_column('adverse_events', 'ai_risk_level')
    # ### end Alembic commands ###
